### ISSUE TITLE
Prettier

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/styleguide-javascript#11]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/48644231-4556d780-e9e2-11e8-862e-e8ce630fd0ba.png" width="30%" /></p>

> Epic: #8 

Integrate [Prettier][], the opinionated code formatter with support for many languages and integrations with most editors. It ensures that all outputted code conforms to a consistent style.

### Configuration

This is one of the main features of Prettier: It already provides the best and recommended style configurations of-out-the-box™.
The only option we will change is the [print width][prettier-docs-pwidth]. It is set to 80 by default which not up-to-date for modern screens (might only be relevant when working in terminals only like e.g. with Vim). It'll be changed to 120 used by all of Arctic Ice Studio's style guides.
The `prettier.config.js` configuration file will be placed in the project root as well as the `.prettierignore` file to also define ignore pattern.

### NPM script/task

To allow to format all sources a `format:pretty` npm script/task will be added to be included in the main `format` script flow.

### False-Positives

To ensure incorrect examples of the style guide won't be fixed by Prettier, the affected lines must be excluded from Prettier by  [adding the `<!-- prettier-ignore -->` handle for HTML][p-d-ign].
Note that this might trigger `remark-lint` when added right above a code block (`no-missing-blank-lines`). This can also be fixed by [adding the `<!--lint disable no-missing-blank-lines-->` handle][rml-ign] as well.

## Tasks

- [x] Install [prettier][npm-prettier] packages.
- [x] Implement `prettier.config.js` configuration file.
- [x] Implement `.prettierignore` ignore pattern file.
- [x] Implement NPM `format:pretty` script/task.
- [x] Format current code base for the first time and fix possible style guide violations using the configured linters of the project.
- [x] Ensure compatibility with Prettier (#11) by adding required _ignore_/_disable_ handles for Prettier and `remark-lint`.

[npm-prettier]: https://www.npmjs.com/package/prettier
[prettier-docs-pwidth]: https://prettier.io/docs/en/options.html#print-width
[prettier]: https://prettier.io
[p-d-ign]: https://prettier.io/docs/en/ignore.html#html
[rml-ign]: https://github.com/remarkjs/remark-lint#configuring-remark-lint
