### ISSUE TITLE
General repository and package documentations and metadata

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/styleguide-javascript#14]
> Epic: #8

The current project repository documentations are not designed for a monorepo layout and will be updated including various badges provided by the great [shields.io][] project.

Further documentations about the project architecture and technologies as well as guides for contributions to develop, run and maintain the project will stay within the packages itself. Minimal instructions might be added later on within a “Getting Started” / “Quick Start” section.

There are also various places that contain outdated documentations and metadata that need to be updated too.

## Tasks

- [x] Update outdated documentations and metadata like copyright comment headers.
- [x] Add a new `.yarnrc` configuration file to set the `save-prefix` option in order to resolve always install and resolve exact dependency versions.
- [x] Add @svengreb as core team contributor to the `CODEOWNERS` file.
- [x] Update project repository SVG assets using GitHub's new `sanitize=true` query parameter to allow rendering SVG's hosted within the repository and served via the `raw.githubusercontent` subdomain.
- [x] Add [shields.io][] badges for
  - latest GitHub release version and changelog
  - deployed ESLint package versions and statistics (downloads)
  - ~~GitHub Actions CI/CD status~~

[shields.io]: https://shields.io
